In [1]:
import numpy as np
import pandas as pd

In [2]:
def load_inputs(npz_path, ps4g_path, sep):
    data = np.load(npz_path, allow_pickle=True)
    final_predictions = data['path']
    background = data['background']
    model_predictions = data['predictions']

    df = pd.read_csv(ps4g_path, sep=sep, header=0)
    gamete = df['gamete'].values
    index = df['gamete_index'].values
    y_labels = list(gamete[index])

    return final_predictions, background, model_predictions, y_labels

In [3]:
npz_path  = "/Users/bm646-admin/Downloads/HMM_CML69_9_100.npz"
npz_path  = "/Users/bm646-admin/Downloads/HMM_CML69_9_100.npz"
ps4g_path = "/Users/bm646-admin/Downloads/CML69.csv"

In [4]:
fp, bg, mp, ylab = load_inputs(npz_path, ps4g_path, sep = "\t")

In [5]:
fp

array([5, 5, 5, ..., 5, 5, 5], shape=(82944,))

In [6]:
bg

array([[0, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 1]], shape=(82944, 29), dtype=int8)

In [7]:
bg.ndim

2

In [7]:
mp

array([5, 5, 5, ..., 5, 5, 5], shape=(82944,))

In [8]:
ylab

['CML103',
 'Ia453',
 'A188',
 'NC350',
 'CML277',
 'CML69',
 'CML52',
 'Ki3',
 'Ki11',
 'CML228',
 'Il14H',
 'CML322',
 'Tzi8',
 'Mo18W',
 'NC358',
 'CML333',
 'M162W',
 'Tx303',
 'HP301',
 'M37W',
 'Ms71',
 'B97',
 'Oh43',
 'Oh7B',
 'K0326Y',
 'P39',
 'Ky21',
 'CML247']